apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 2.0.0-NOD-532-Aggiungere-Application-Insights-e-stampare-alert-PPT_SYSTEM_ERROR
appVersion: 2.0.0-NOD-532-Aggiungere-Application-Insights-e-stampare-alert-PPT_SYSTEM_ERROR
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: fdrnodo
