apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 2.0.0-NOD-519-risposta-ppt-system-error-invio-blob-azure
appVersion: 2.0.0-NOD-519-risposta-ppt-system-error-invio-blob-azure
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: fdrnodo
