apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 1.0.0-SNAPSHOT
appVersion: 1.0.0-SNAPSHOT
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: fdrnodo
