version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:1bb1adb84f2b90e0c1b5ddd1ed185bbf98249dbc6f216968412ca4b3fe6f14b9
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - API_SUBSCRIPTION_KEY=${sub_key}
      - FLOW_SIZE=${flow_size}
      - VARS=/environments/${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
    command: run --quiet /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:bc5eac5eafc581aeda3008b4b1f07ebba230de2f27d47767129a6a905c84f470
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx_${env}.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

