apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 0.74.0
appVersion: 2.3.3-284-PIDM-1482-fix-non-blocking-error
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: fdrnodo
