microservice-chart: &microservice-chart
  namespace: "fdr"
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-nodo-dei-pagamenti
    tag: 2.2.2-198-PAGOPA-2871-fix
  canaryDelivery:
    create: false
  terminationGracePeriodSeconds: 140
  livenessProbe:
    httpGet:
      path: /alive
      port: 8558
    initialDelaySeconds: 15
    failureThreshold: 10
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 8558
    initialDelaySeconds: 10
    failureThreshold: 10
    periodSeconds: 5
  externalConfigMapFiles:
    create: true
    configMaps:
      - name: fdr-cacerts
        key: cacerts
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "640M"
      cpu: "512m"
    limits:
      memory: "8Gi"
      cpu: "2560m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    triggers:
      - type: cpu
        metricType: Utilization
        metadata:
          value: "80"
      - type: memory
        metricType: Utilization
        metadata:
          value: "85"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
              - type: Pods
                value: 1
                periodSeconds: 20
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Percent
                value: 100
                periodSeconds: 20
  envConfig:
    AZURE_INSIGHTS_ENABLED: "true"
    APPLICATIONINSIGHTS_ROLE_NAME: "fdr-nodo"
    MANAGEMENT_HTTP_PORT: "8558"
    MANAGEMENT_HTTP_BIND_HOST: "0.0.0.0"
    MANAGEMENT_HTTP_BIND_PORT: "8558"
    SERVICE_HTTP_PORT: "8080"
    SERVICE_HTTP_BIND_HOST: "0.0.0.0"
    SERVICE_HTTP_BIND_PORT: "8080"
    PROMETHEUS_HOST: "0.0.0.0"
    PROMETHEUS_PORT: "9091"
    MICROMETER_HOST: "0.0.0.0"
    MICROMETER_PORT: "9092"
    TZ: "Europe/Rome"
    AKKA_SYSTEM_NAME: "pagopafdrnodo"
    JAVA_OPTS: >-
      -Dlogback.configurationFile=/mnt/file-config/logback.xml -Dconfig.app=/mnt/file-config/config-app.conf -Dapp.bundle.cacerts.path=/mnt/file-config-external/fdr-cacerts/cacerts -Duser.language=it -Duser.country=IT -Duser.timezone=Europe/Rome -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3000 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    DB_FDR_URL: jdbc:postgresql://fdr-db.d.internal.postgresql.pagopa.it:6432/fdr?sslmode=require&prepareThreshold=0
    DB_FDR_USER: fdr
    INSTANCE: DEV
    AZURE_STORAGE_FDR1_FLOWS_BLOB_NAME: "fdr1-flows"
    AZURE_STORAGE_RE_PAYLOAD_BLOB_NAME: "re-payload"
    MONGO_DATABASE_NAME: "fdr-re"
    MONGO_METADATA_DOCUMENT_NAME: "fdr1-metadata"
    MONGO_EVENTS_DOCUMENT_NAME: "events"
    ADDITIONAL_FDR_VALIDATIONS: "true"
    SERVICE_IDENTIFIER: "FDR001DEV"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-connection-string"
    AZURE_STORAGE_BLOB_CONNECTION_STRING: "fdr-sa-connection-string"
    AZURE_STORAGE_RE_CONNECTION_STRING: "fdr-re-sa-connection-string"
    API_CONFIG_CACHE_SUBSCRIPTION_KEY: "api-config-cache-subscription-key-string"
    FDR_SUBSCRIPTION_KEY: "fdr-internal-product-subscription-key"
    FDR_LEGACY_SUBSCRIPTION_KEY: "fdr-legacy-subscription-key"
    DB_FDR_PASSWORD: "db-fdr-password"
    MONGO_CONNECTION_STRING: "mongodb-re-connection-string"
  keyvault:
    name: "pagopa-d-fdr-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envFieldRef:
    MANAGEMENT_HTTP_HOST: "status.podIP"
    SERVICE_HTTP_HOST: "status.podIP"
    MICROMETER_HOSTNAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
    CINNAMON_HOST: "metadata.name"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
    APP_NAME: "metadata.labels['app.kubernetes.io/name']"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"
  serviceAccount:
    name: "fdr-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #micrometer
        targetPort: 9092
        path: /
      - interval: 10s #cinnamon
        targetPort: 9091
        path: /metrics
  ports:
    - 8080 #http
    - 8558 #akka-management
    - 9091 #cinnamon
    - 9092 #micrometer
    - 3000 #jmx debug port
  service:
    type: ClusterIP
    ports:
      - 8080 #http
      - 9091 #cinnamon
      - 9092 #micrometer
      - 3000
fdrnodo:
  !!merge <<: *microservice-chart
  nameOverride: ""
  fullnameOverride: ""
  ingress:
    create: true
    host: "weudev.fdr.internal.dev.platform.pagopa.it"
    path: /pagopa-fdr-nodo-service/(.*)
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
