basecronjob: &basecronjob
  namespace: "nodo-cron"
  concurrencyPolicy: "Allow"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  parallelism: 1
  terminationGracePeriodSeconds: 140
  image:
    repository: pagopadcommonacr.azurecr.io/pagopanodo4nododeipagamenti
    tag: "3.15.1-SNAPSHOT"
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "6Gi"
      cpu: "2048m"
    limits:
      memory: "8Gi"
      cpu: "2560m"
  providedVolumeMount:
    create: true
    envSecrets:
      azurestorageaccountname: "azurestorageaccountname"
      azurestorageaccountkey: "azurestorageaccountkey"
  externalConfigMap:
    create: true
    configMaps:
      - name: nodo-cacerts
        key: cacerts
  envConfig:
    AZURE_INSIGHTS_ENABLED: "true"
    APPLICATIONINSIGHTS_ROLE_NAME: "nodo-cron-it-ndp"
    MANAGEMENT_HTTP_PORT: "8558"
    MANAGEMENT_HTTP_BIND_HOST: "0.0.0.0"
    MANAGEMENT_HTTP_BIND_PORT: "8558"
    SERVICE_HTTP_PORT: "8080"
    SERVICE_HTTP_BIND_HOST: "0.0.0.0"
    SERVICE_HTTP_BIND_PORT: "8080"
    PROMETHEUS_HOST: "0.0.0.0"
    PROMETHEUS_PORT: "9091"
    MICROMETER_HOST: "0.0.0.0"
    MICROMETER_PORT: "9092"
    TZ: "Europe/Rome"
    AKKA_SYSTEM_NAME: "nodo"
    JAVA_OPTS: >-
      -Dlogback.configurationFile=/mnt/file-config/logback.xml -Dconfig.app=/mnt/file-config/config-app.conf -Dapp.bundle.casogei.path=/mnt/secrets-store/casogei-cert-pem -Dapp.bundle.cacerts.path=/mnt/file-config-external/nodo-cacerts/cacerts -Duser.language=it -Duser.country=IT -Duser.timezone=Europe/Rome -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3000 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    DB_ONLINE_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=online
    DB_OFFLINE_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=offline
    DB_RE_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=re
    DB_WFESP_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=wfesp
    DB_ONLINE_USER: online
    DB_OFFLINE_USER: offline
    DB_RE_USER: re
    DB_WFESP_USER: wfesp
    INSTANCE: IT
    SERVICE_IDENTIFIER: NDP001IT
  secretProvider:
    create: true
    envSecrets:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "azure-insight-connection-string"
      AZURE_EVENT_HUB_RE_CONNECTION_STRING: "azure-event-hub-re-connection-string"
      AZURE_EVENT_HUB_BIZ_EVT_CONNECTION_STRING: "azure-event-hub-biz-evt-connection-string"
      GEC_FEES_SUBSCRIPTION_KEY: "gec-fees-subscription-key-string"
      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "api-config-cache-subscription-key-string"
      FORWARDER_SUBSCRIPTION_KEY: "node-forwarder-subscription-key-string"
      DB_CONFIG_PASSWORD: "db-cfg-password"
      DB_ONLINE_PASSWORD: "db-online-password"
      DB_OFFLINE_PASSWORD: "db-offline-password"
      DB_RE_PASSWORD: "db-re-password"
      DB_WFESP_PASSWORD: "db-wfesp-password"
      CASOGEI_CERT_PEM: "casogei-cert-pem"
    keyvault:
      name: "pagopa-d-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envFieldRef:
    MANAGEMENT_HTTP_HOST: "status.podIP"
    SERVICE_HTTP_HOST: "status.podIP"
    MICROMETER_HOSTNAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
    CINNAMON_HOST: "metadata.name"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo-cron"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo-cron
                operator: In
                values:
                  - "true"
  podMonitor:
    create: true
    podMetricsEndpoints:
      - interval: 10s #micrometer
        port: 9092
        path: /
      - interval: 10s #cinnamon
        port: 9091
        path: /metrics
cj-annullamento-rpt:
  !!merge <<: *basecronjob
  schedule: "2 * * * *"
  args: [annullamentoRptMaiRichiesteDaPm]
cj-ftp-upload:
  !!merge <<: *basecronjob
  schedule: "4 * * * *"
  args: [ftpUpload]
cj-genera-rend-bollo:
  !!merge <<: *basecronjob
  schedule: "6 * * * *"
  args: [generaRendicontazioneBollo]
  fileShare:
    create: true
    folders:
      - name: firmatore
        readOnly: false
        mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
cj-mod3-cancel-v1:
  !!merge <<: *basecronjob
  schedule: "8 * * * *"
  args: [mod3CancelV1]
cj-mod3-cancel-v2:
  !!merge <<: *basecronjob
  schedule: "10 * * * *"
  args: [mod3CancelV2]
cj-pa-invia-rt:
  !!merge <<: *basecronjob
  schedule: "12 * * * *"
  args: [paInviaRt]
  resources:
    requests:
      memory: "10Gi"
      cpu: "3584m"
    limits:
      memory: "12Gi"
      cpu: "4096m"
cj-pa-invia-rt-recovery:
  !!merge <<: *basecronjob
  schedule: "14 * * * *"
  args: [paInviaRtRecovery]
  resources:
    requests:
      memory: "10Gi"
      cpu: "3584m"
    limits:
      memory: "12Gi"
      cpu: "4096m"
cj-pa-retry-invia-rt-neg:
  !!merge <<: *basecronjob
  schedule: "16 * * * *"
  args: [paRetryPaInviaRtNegative]
cj-pa-send-rt:
  !!merge <<: *basecronjob
  schedule: "18 * * * *"
  args: [paSendRt]
cj-pos-retry-send-payment-res:
  !!merge <<: *basecronjob
  schedule: "20 * * * *"
  args: [positionRetrySendPaymentResult]
cj-psp-chiedi-avanz-rpt:
  !!merge <<: *basecronjob
  schedule: "22 * * * *"
  args: [pspChiediAvanzamentoRpt]
cj-psp-chiedi-lista-rt:
  !!merge <<: *basecronjob
  schedule: "24 * * * *"
  args: [pspChiediListaAndChiediRt]
  resources:
    requests:
      memory: "10Gi"
      cpu: "3584m"
    limits:
      memory: "12Gi"
      cpu: "4096m"
cj-psp-retry-ack-negative:
  !!merge <<: *basecronjob
  schedule: "26 * * * *"
  args: [pspRetryAckNegative]
cj-refresh-configuration:
  namespace: "nodo-cron"
  schedule: "28 * * * *"
  image:
    repository: "curlimages/curl"
    tag: "latest"
    pullPolicy: "Always"
  command:
    - "/bin/sh"
    - "-c"
    - "echo \"Starting...\"; export URL=http://nodoreplica.nodo.svc.cluster.local:8080/jobs/trigger/refreshConfiguration?cron=true; echo \"Call '$URL'\"; curl -m 300 $URL; echo \"\"; echo \"Done\";"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "150m"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo-cron"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo-cron
                operator: In
                values:
                  - "true"
cj-retry-pa-attiva-rpt:
  !!merge <<: *basecronjob
  schedule: "30 * * * *"
  args: [paRetryAttivaRpt]
cj-rt-pull-recovery-push:
  !!merge <<: *basecronjob
  schedule: "32 * * * *"
  args: [rtPullRecoveryPush]
  resources:
    requests:
      memory: "10Gi"
      cpu: "3584m"
    limits:
      memory: "12Gi"
      cpu: "4096m"
