fdrnodo:
  namespace: "fdr"
  nameOverride: ""
  fullnameOverride: ""
  terminationGracePeriodSeconds: 140
  image:
    repository: pagopadcommonacr.azurecr.io/pagopafdrnododeipagamenti
    tag: 1.0.0-SNAPSHOT
  livenessProbe:
    httpGet:
      path: /alive
      port: 8558
    initialDelaySeconds: 15
    failureThreshold: 10
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 8558
    initialDelaySeconds: 10
    failureThreshold: 10
    periodSeconds: 5
  externalConfigMap:
    create: true
    configMaps:
      - name: fdr-cacerts
        key: cacerts
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "6Gi"
      cpu: "2048m"
    limits:
      memory: "8Gi"
      cpu: "2560m"
  autoscaling:
    enable: true
    triggers:
      - type: cpu
        metricType: Utilization
        metadata:
          value: "70"
      - type: memory
        metricType: Utilization
        metadata:
          value: "80"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
              - type: Pods
                value: 1
                periodSeconds: 20
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Percent
                value: 100
                periodSeconds: 20
  envConfig:
    MANAGEMENT_HTTP_PORT: "8558"
    MANAGEMENT_HTTP_BIND_HOST: "0.0.0.0"
    MANAGEMENT_HTTP_BIND_PORT: "8558"
    SERVICE_HTTP_PORT: "8080"
    SERVICE_HTTP_BIND_HOST: "0.0.0.0"
    SERVICE_HTTP_BIND_PORT: "8080"
    PROMETHEUS_HOST: "0.0.0.0"
    PROMETHEUS_PORT: "9091"
    MICROMETER_HOST: "0.0.0.0"
    MICROMETER_PORT: "9092"
    TZ: "Europe/Rome"
    AKKA_SYSTEM_NAME: "pagopafdrnodo"
    JAVA_OPTS: >-
      -Dlogback.configurationFile=/mnt/file-config/logback.xml -Dconfig.app=/mnt/file-config/config-app.conf -Duser.language=it -Duser.country=IT  -Duser.timezone=Europe/Rome  -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote=true  -Dcom.sun.management.jmxremote.port=3000  -Dcom.sun.management.jmxremote.rmi.port=3000  -Djava.rmi.server.hostname=127.0.0.1  -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false
    DB_FDR_URL: jdbc:postgresql://ndp.d.db-nodo-pagamenti.com:6432/nodo?sslmode=require&prepareThreshold=0&currentSchema=offline
    DB_FDR_USER: fdr
    INSTANCE: DEV
    EVENT_HUB_NAME: "fdr-re"
    BLOB_RE_CONTAINER_NAME: "payload"
    AZURE_STORAGE_BLOB_NAME: "xmlsharefile"
    ADDITIONAL_FDR_VALIDATIONS: true
  secretProvider:
    create: true
    envSecrets:
      EVENT_HUB_RE_CONNECTION_STRING: "azure-event-hub-re-connection-string"
      AZURE_STORAGE_BLOB_CONNECTION_STRING: "fdr-sa-connection-string"
      BLOB_RE_CONNECTION_STRING: "fdr-re-sa-connection-string"
      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "api-config-cache-subscription-key-string"
      DB_FDR_PASSWORD: "db-fdr-password"
    keyvault:
      name: "pagopa-d-neu-fdr-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envFieldRef:
    MANAGEMENT_HTTP_HOST: "status.podIP"
    SERVICE_HTTP_HOST: "status.podIP"
    MICROMETER_HOSTNAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
    CINNAMON_HOST: "metadata.name"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
    APP_NAME: "metadata.labels['app.kubernetes.io/name']"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #micrometer
        targetPort: 9092
        path: /
      - interval: 10s #cinnamon
        targetPort: 9091
        path: /metrics
  ports:
    - 8080 #http
    - 8558 #akka-management
    - 9091 #cinnamon
    - 9092 #micrometer
    - 3000 #jmx debug port
  service:
    type: ClusterIP
    ports:
      - 8080 #http
      - 9091 #cinnamon
      - 9092 #micrometer
  ingress:
    create: true
    host: "neudev.fdr.internal.dev.platform.pagopa.it"
    path: /pagopa-fdr-nodo-service(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m