nodo:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  terminationGracePeriodSeconds: 140
  image:
    repository: pagopadcommonacr.azurecr.io/pagopanodo4nododeipagamenti
    tag: 1.0.0-SNAPSHOT
  livenessProbe:
    httpGet:
      path: /alive
      port: 8558
    initialDelaySeconds: 15
    failureThreshold: 10
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 8558
    initialDelaySeconds: 10
    failureThreshold: 10
    periodSeconds: 5
  externalConfigMap:
    create: true
    configMaps:
      - name: nodo-cacerts
        key: cacerts
  providedVolumeMount:
    create: true
    envSecrets:
      azurestorageaccountname: "azurestorageaccountname"
      azurestorageaccountkey: "azurestorageaccountkey"
    folders:
      - name: firmatore
        readOnly: false
        mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "6Gi"
      cpu: "2048m"
    limits:
      memory: "8Gi"
      cpu: "2560m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    triggers:
      - type: cpu
        metricType: Utilization
        metadata:
          value: "70"
      - type: memory
        metricType: Utilization
        metadata:
          value: "80"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
              - type: Pods
                value: 1
                periodSeconds: 20
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Percent
                value: 100
                periodSeconds: 20
  envConfig:
    AZURE_INSIGHTS_ENABLED: "true"
    APPLICATIONINSIGHTS_ROLE_NAME: "nodo-it-ndp"
    MANAGEMENT_HTTP_PORT: "8558"
    MANAGEMENT_HTTP_BIND_HOST: "0.0.0.0"
    MANAGEMENT_HTTP_BIND_PORT: "8558"
    SERVICE_HTTP_PORT: "8080"
    SERVICE_HTTP_BIND_HOST: "0.0.0.0"
    SERVICE_HTTP_BIND_PORT: "8080"
    PROMETHEUS_HOST: "0.0.0.0"
    PROMETHEUS_PORT: "9091"
    MICROMETER_HOST: "0.0.0.0"
    MICROMETER_PORT: "9092"
    TZ: "Europe/Rome"
    AKKA_SYSTEM_NAME: "nodo"
    JAVA_OPTS: >-
      -Dlogback.configurationFile=/mnt/file-config/logback.xml  -Dconfig.app=/mnt/file-config/config-app.conf  -Dapp.bundle.casogei.path=/mnt/secrets-store/casogei-cert-pem  -Dapp.bundle.cacerts.path=/mnt/file-config-external/nodo-cacerts/cacerts  -Duser.language=it  -Duser.country=IT  -Duser.timezone=Europe/Rome  -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote=true  -Dcom.sun.management.jmxremote.port=3000  -Dcom.sun.management.jmxremote.rmi.port=3000  -Djava.rmi.server.hostname=127.0.0.1  -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false
    DB_ONLINE_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=online
    DB_OFFLINE_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=offline
    DB_RE_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=re
    DB_WFESP_URL: jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo-replica?sslmode=require&prepareThreshold=0&currentSchema=wfesp
    DB_ONLINE_USER: online
    DB_OFFLINE_USER: offline
    DB_RE_USER: re
    DB_WFESP_USER: wfesp
    INSTANCE: IT
    SERVICE_IDENTIFIER: NDP001IT
  secretProvider:
    create: true
    envSecrets:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "azure-insight-connection-string"
      AZURE_EVENT_HUB_RE_CONNECTION_STRING: "azure-event-hub-re-connection-string"
      AZURE_EVENT_HUB_BIZ_EVT_CONNECTION_STRING: "azure-event-hub-biz-evt-connection-string"
      GEC_FEES_SUBSCRIPTION_KEY: "gec-fees-subscription-key-string"
      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "api-config-cache-subscription-key-string"
      FORWARDER_SUBSCRIPTION_KEY: "node-forwarder-subscription-key-string"
      DB_CONFIG_PASSWORD: "db-cfg-password"
      DB_ONLINE_PASSWORD: "db-online-password"
      DB_OFFLINE_PASSWORD: "db-offline-password"
      DB_RE_PASSWORD: "db-re-password"
      DB_WFESP_PASSWORD: "db-wfesp-password"
      CASOGEI_CERT_PEM: "casogei-cert-pem"
    keyvault:
      name: "pagopa-d-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envFieldRef:
    MANAGEMENT_HTTP_HOST: "status.podIP"
    SERVICE_HTTP_HOST: "status.podIP"
    MICROMETER_HOSTNAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
    CINNAMON_HOST: "metadata.name"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #micrometer
        targetPort: 9092
        path: /
      - interval: 10s #cinnamon
        targetPort: 9091
        path: /metrics
  ports:
    - 8080 #http
    - 8558 #akka-management
    - 9091 #cinnamon
    - 9092 #micrometer
    - 3000 #jmx debug port
  service:
    type: ClusterIP
    ports:
      - 8080 #http
      - 9091 #cinnamon
      - 9092 #micrometer
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /nodo-replica(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
