apiVersion: v2
name: wisp-soap-converter-chart
description: Wisp Soap Conveter
type: application
version: 2.17.0
appVersion: 0.1.1-41-uat_prd_files
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: wispsoapconverter
