apiVersion: v2
name: wisp-soap-converter-chart
description: Wisp Soap Conveter
type: application
version: 2.29.0
appVersion: 0.2.1-54-redirect_uri
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: wispsoapconverter
