apiVersion: v2
name: wisp-soap-converter-chart
description: Wisp Soap Conveter
type: application
version: 2.19.0
appVersion: 0.1.2-43-newimage
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: wispsoapconverter
