apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 0.21.0
appVersion: 2.1.9-104-PAGOPA-2600-housekeeping-evh-qi
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: prfnodo
