apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 0.10.0
appVersion: 2.1.9-58-PAGOPA-2394
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: fdrnodo
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: prfnodo
