name: Performance Test

on:
  #  schedule:
  #    - cron: '35 16 * * *'

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
      test-type:
        required: true
        type: choice
        description: Select the Test Type
        options:
          - ramping
          - constant
          - load
          - load-6h
          - smoke
          - soak
          - spike
          - stress
      script-name:
        required: true
        type: choice
        description: Select the Script Name
        options:
          - happy_case_scenario
          - only_nodoInviaFlussoRendicontazione_scenario
      flow-size:
        required: true
        type: number
        description: Select the number of payments sent in flow
        default: 5

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  run_performance_test:
    name: Performance test on ${{(github.event.inputs == null && 'dev') || inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{(github.event.inputs == null && 'dev') || inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Run k6 script
        run: |
          cd ./performance-test
          sh ./run_performance_test.sh ${{ inputs.environment }} ${{ inputs.test-type }} ${{ inputs.script-name }} fdr1_k6 ${{ secrets.INTEGRATION_TEST_SUBSCRIPTION_KEY }} ${{ inputs.flow-size }}
        
