cronnodo:
  namespace: "fdr"
  schedule: "4 * * * *"
  args: [ ftpUpload ]
  concurrencyPolicy: "Allow"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  parallelism: 1
  terminationGracePeriodSeconds: 140
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-nodo-dei-pagamenti
    tag: 2.1.9-40-test-deploy
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "6Gi"
      cpu: "2048m"
    limits:
      memory: "8Gi"
      cpu: "2560m"
  externalConfigMap:
    create: true
    configMaps:
      - name: fdr-cacerts
        key: cacerts
  envConfig:
    AZURE_INSIGHTS_ENABLED: "true"
    APPLICATIONINSIGHTS_ROLE_NAME: "fdr-nodo-cron"
    MANAGEMENT_HTTP_PORT: "8558"
    MANAGEMENT_HTTP_BIND_HOST: "0.0.0.0"
    MANAGEMENT_HTTP_BIND_PORT: "8558"
    SERVICE_HTTP_PORT: "8080"
    SERVICE_HTTP_BIND_HOST: "0.0.0.0"
    SERVICE_HTTP_BIND_PORT: "8080"
    PROMETHEUS_HOST: "0.0.0.0"
    PROMETHEUS_PORT: "9091"
    MICROMETER_HOST: "0.0.0.0"
    MICROMETER_PORT: "9092"
    TZ: "Europe/Rome"
    AKKA_SYSTEM_NAME: "pagopafdrnodo"
    JAVA_OPTS: >-
      -Dlogback.configurationFile=/mnt/file-config/logback.xml -Dconfig.app=/mnt/file-config/config-app.conf -Dapp.bundle.cacerts.path=/mnt/file-config-external/fdr-cacerts/cacerts -Duser.language=it -Duser.country=IT -Duser.timezone=Europe/Rome -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3000 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    DB_FDR_URL: jdbc:postgresql://pagopa-d-weu-fdr-flexible-postgresql.postgres.database.azure.com:6432/fdr?sslmode=require&prepareThreshold=0
    DB_FDR_USER: fdr
    INSTANCE: DEV
    EVENT_HUB_NAME: "fdr-re"
    BLOB_RE_CONTAINER_NAME: "payload"
    AZURE_STORAGE_BLOB_NAME: "xmlsharefile"
    ADDITIONAL_FDR_VALIDATIONS: "true"
    AZURE_QUEUE_NAME: "queueconversion"
    EVENT_HUB_FLOWTX_NAME: "fdr-qi-flows"
    EVENT_HUB_REPORTEDIUV_NAME: "fdr-qi-reported-iuv"
  secretProvider:
    create: true
    envSecrets:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-connection-string"
      EVENT_HUB_RE_CONNECTION_STRING: "azure-event-hub-re-connection-string"
      AZURE_STORAGE_BLOB_CONNECTION_STRING: "fdr-sa-connection-string"
      AZURE_QUEUE_CONNECTION_STRING: "fdr-sa-connection-string"
      BLOB_RE_CONNECTION_STRING: "fdr-re-sa-connection-string"
      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "api-config-cache-subscription-key-string"
      FDR_SUBSCRIPTION_KEY: "fdr-subscription-key-string"
      FDR_LEGACY_SUBSCRIPTION_KEY: "fdr-legacy-subscription-key"
      DB_FDR_PASSWORD: "db-fdr-password"
      EVENT_HUB_REPORTEDIUV_CONNECTION_STRING: "fdr-qi-reported-iuv-tx-connection-string"
      EVENT_HUB_FLOWTX_CONNECTION_STRING: "fdr-qi-flows-tx-connection-string"
    keyvault:
      name: "pagopa-d-fdr-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envFieldRef:
    MANAGEMENT_HTTP_HOST: "status.podIP"
    SERVICE_HTTP_HOST: "status.podIP"
    MICROMETER_HOSTNAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
    CINNAMON_HOST: "metadata.name"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
    APP_NAME: "metadata.labels['app.kubernetes.io/name']"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  podMonitor:
    create: true
    podMetricsEndpoints:
      - interval: 10s #micrometer
        port: 9092
        path: /
      - interval: 10s #cinnamon
        port: 9091
        path: /metrics
